### ISSUE TITLE
why is this deprecated?

### ISSUE THREAD

**Issue by natedogs911** [big-data-europe/docker-zookeeper#2]
Hello,

I noticed this repo states it's deprecated however [docker-kafka](https://github.com/big-data-europe/docker-kafka) still lists this project in the documentation.

Is there a reason that this image should not be used or it is simply no longer maintained?

thanks.

**Comment by earthquakesan** [comment]
Hi @natedogs911!

The pilots, in particular [sc6](https://github.com/big-data-europe/pilot-sc6-cycle2/blob/master/sc6-zookeeper/Dockerfile) is extending official zookeeper image. This repo is not maintained any more, that what deprecated means.
